---
functional:
  - Можно выбирать один из 15ти языков программирования;
  - Победа присуждается тому, кто перввый написал код для решения задачи
  - Во время игры можно видеть действия соперника 
  - Можно создать игру и ждать соперника
  - Можно скинуть ссылку на созданную игру конкретному пользователю
  - Можно вступить в уже созданную другим пользователем игру
  - При создании игры можно выбирать: уровень сложноссти, тип игры (против пользователя/друга/бота), время игры (от 3х до 60ти минут), выбрать задачу по названию или по тегу
  - В созданной игре можно выбирать: язык (ru/en), выбирать ЯП, на котором удобно выполнять задание. Есть описание задачи и примеры решения
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы;
  - Сайт должен быть безопасным и защищать данные пользователя;
  - Сайт должен быть удобным на мобильном устройстве;
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров;
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей);
  - Нужно иметь возможность переключать язык на главной странице;
  - Регистрация пользователя возможна по почте, через профили GitHub/Discord, логически еще можно добавить через Хекслет;
  - Авторизация пользователя возможна по почте, через профили GitHub/Discord, логически еще можно добавить через Хекслет;
  - При помощи расширения можно наблюдать за игрой, не заходя на сайт
  - На главной странице рейтинг. Доступна фильтрация за текущую неделе, за текущий месяц, за все время
  - Можно смотреть за игрой как зритель
  - Во время игры можно общаться с соперником и зрителями
  
implicit:
  - Во время игры можно общаться с соперником и зрителями
  - Можно наблюдать за игрой как зритель
  - Нажав на никнейм пользователя, можно посмотреть основную информацию: предпочитаемый ЯП, дата регистрации, ачивки, рейтинг, количество проведенных игр, количество заработанных очков, разбивка по ЯП , активность 
  - В лобби отображаются игроки онлайн
  - В лобби есть общий чат
  - Любому пользователю можно отправить приватное сообщение, добавить в друзья
  - При регистрации пользователя идет проверка правильности заполнения полей: корректный вид почты, пароль от 6 до 16 символов
